// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBHaLHTJmprwrg-w8F_d60z3BlQi6K51U',
    appId: '1:664736872812:web:d56f0ddf04a9ed73595b49',
    messagingSenderId: '664736872812',
    projectId: 'stitch-app-bfb7d',
    authDomain: 'stitch-app-bfb7d.firebaseapp.com',
    storageBucket: 'stitch-app-bfb7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE_lcs322jGdna9Q86f-tdw0qz-lMohJQ',
    appId: '1:664736872812:android:ab60340b64c6c097595b49',
    messagingSenderId: '664736872812',
    projectId: 'stitch-app-bfb7d',
    storageBucket: 'stitch-app-bfb7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Xq92KS3WNNWHHOpPRUQR4sLnRAZ8bB4',
    appId: '1:664736872812:ios:da5ba92052c47fff595b49',
    messagingSenderId: '664736872812',
    projectId: 'stitch-app-bfb7d',
    storageBucket: 'stitch-app-bfb7d.firebasestorage.app',
    iosBundleId: 'com.example.stitchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Xq92KS3WNNWHHOpPRUQR4sLnRAZ8bB4',
    appId: '1:664736872812:ios:da5ba92052c47fff595b49',
    messagingSenderId: '664736872812',
    projectId: 'stitch-app-bfb7d',
    storageBucket: 'stitch-app-bfb7d.firebasestorage.app',
    iosBundleId: 'com.example.stitchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBHaLHTJmprwrg-w8F_d60z3BlQi6K51U',
    appId: '1:664736872812:web:c9f7c7106ef9223e595b49',
    messagingSenderId: '664736872812',
    projectId: 'stitch-app-bfb7d',
    authDomain: 'stitch-app-bfb7d.firebaseapp.com',
    storageBucket: 'stitch-app-bfb7d.firebasestorage.app',
  );
}
